spring.application.name=AliyevAuto

security.jwt.secret=V2VUaGltSXM0QmFzZTY0U2VjcmV0Rm9yQWxpeWV2QXV0b0pXVFRlc3QxMjM0NTY3ODkwMTIzNDU2Nzg5MA==
security.jwt.access-expiration=900000
security.jwt.refresh-expiration=604800000